name: auth
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sign_button: ^2.0.0
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_storage: "^10.0.1"
  image_picker: ^0.8.3+2

  flutter_signin_button: ^2.0.0
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true



